import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/LegalShell";

export const metadata: Metadata = {
  title: "Terms of Use · LumiDoc",
  description: "The terms governing your use of LumiDoc.",
};

export default function TermsPage() {
  return (
    <LegalShell
      eyebrow="Legal"
      title="Terms of Use"
      intro="These terms govern your access to and use of LumiDoc. By using the service, you agree to them."
      updated="11 June 2026"
    >
      <h2>1. The service</h2>
      <p>
        LumiDoc (&ldquo;the Service&rdquo;) lets you upload documents and ask questions about them,
        receiving answers generated by AI with references to the source material. The Service is
        provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis.
      </p>

      <h2>2. Your account</h2>
      <p>
        You are responsible for safeguarding your account credentials and for all activity that
        occurs under your account. You must provide accurate information and keep it up to date.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          Upload content you do not have the right to use or that infringes third-party rights.
        </li>
        <li>Use the Service to violate any applicable law or regulation.</li>
        <li>Attempt to disrupt, reverse-engineer, or gain unauthorised access to the Service.</li>
        <li>Resell or redistribute the Service without written permission.</li>
      </ul>

      <h2>4. Your content</h2>
      <p>
        You retain all rights to the documents and content you upload. You grant us a limited
        licence to process that content solely to provide the Service to you. We do not use your
        content to train AI models. See our <a href="/privacy-policy">Privacy Policy</a> for
        details.
      </p>

      <h2>5. AI-generated answers</h2>
      <p>
        Answers are generated by automated systems and may contain errors. They are provided for
        informational purposes only and do not constitute legal, financial, or professional advice.
        Always verify important information against the cited sources.
      </p>

      <h2>6. Availability and changes</h2>
      <p>
        We may modify, suspend, or discontinue any part of the Service at any time. We will make
        reasonable efforts to notify you of material changes to these terms.
      </p>

      <h2>7. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, LumiDoc shall not be liable for any indirect,
        incidental, or consequential damages arising from your use of the Service.
      </p>

      <h2>8. Governing law</h2>
      <p>
        These terms are governed by the laws of the European Union and the jurisdiction in which the
        Service operator is established, without regard to conflict-of-law principles.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions about these terms? Reach us at{" "}
        <a href="mailto:hello@lumidoc.app">hello@lumidoc.app</a>.
      </p>
    </LegalShell>
  );
}
